language: node_js
node_js:
- 8.0.0
branches:
  only:
  - master

install: npm install

before_script:
- git config --global user.name "afucher"
- git config --global user.email "arthurfucher@gmail.com"
- sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml

script: npm run build